repo = "/storage7/NewCluster/snapshots"
imin = 1
imax = 101
version = "1.0"
overwrite = true
nload = 160
nthread = 8
walltime = 24.0
nchunk = 8000

sim_publication = "https://doi.org/10.48550/arXiv.2507.06301"
sim_description_common = """
This file contains snapshot data of NewCluster simulation.
For any use of this data, please cite the original publication (Han et al.):
{sim_publication}
Use RUR library to efficiently handle and analyze the data:
https://github.com/sanhancluster/rur
Alternatively, use Pyramis library:
https://github.com/sanhancluster/pyramis"""


[dataset_kw]
compression = "lzf"
shuffle = true
fletcher32 = true
chunks = true


[converted_dtypes_part]
star = [
  ["x","f8"], ["y","f8"], ["z","f8"],
  ["vx","f4"], ["vy","f4"], ["vz","f4"],
  ["m","f4"], ["id","i4"], ["level","i1"],
  ["family","i1"], ["tag","i1"], ["epoch","f4"], ["metal","f4"], ["m0","f4"],
  ["H","f4"], ["O","f4"], ["Fe","f4"], ["Mg","f4"],
  ["C","f4"], ["N","f4"], ["Si","f4"], ["S","f4"], ["D","f4"],
  ["rho0","f4"], ["partp","i4"], ["cpu","i2"],
]
dm = [
  ["x","f8"], ["y","f8"], ["z","f8"],
  ["vx","f4"], ["vy","f4"], ["vz","f4"],
  ["m","f4"], ["id","i4"], ["level","i1"],
  ["family","i1"], ["tag","i1"], ["partp","i4"], ["cpu","i2"],
]
cloud = [
  ["x","f8"], ["y","f8"], ["z","f8"],
  ["vx","f4"], ["vy","f4"], ["vz","f4"],
  ["m","f4"], ["id","i4"], ["level","i1"],
  ["family","i1"], ["tag","i1"], ["partp","i4"], ["cpu","i2"],
]
tracer = [
  ["x","f8"], ["y","f8"], ["z","f8"],
  ["m","f4"], ["id","i4"], ["level","i1"],
  ["family","i1"], ["tag","i1"], ["partp","i4"], ["cpu","i2"],
]
sink = [
  ["x","f8"], ["y","f8"], ["z","f8"],
  ["vx","f4"], ["vy","f4"], ["vz","f4"],
  ["m","f4"], ["id","i4"],
  ["tform","f4"], ["dM","f4"], ["dMBH","f4"], ["dMEd","f4"], ["Esave","f4"],
  ["jx","f4"], ["jy","f4"], ["jz","f4"],
  ["sx","f4"], ["sy","f4"], ["sz","f4"], ["spinmag","f4"],
]


[converted_dtypes_cell]
cell = [
    ["x","f8"], ["y","f8"], ["z","f8"], ["level","i1"],
    ["rho","f4"], ["vx","f4"], ["vy","f4"], ["vz","f4"], ["P","f4"],
    ["metal","f4"], ["H","f4"], ["O","f4"], ["Fe","f4"], ["Mg","f4"],
    ["C","f4"], ["N","f4"], ["Si","f4"], ["S","f4"], ["D","f4"],
    ["d1","f4"], ["d2","f4"], ["d3","f4"], ["d4","f4"],
    ["refmask","f4"], ["sigma","f4"], ["pot","f4"], ["cpu","i2"],
]
