repo = "/automnt/data83/NewCluster/snapshots"
version = "1.2"
overwrite = true
nload = 480
nthread = 8
walltime = 90.0
nchunk = 8000
output = "../hdf"

sim_publication = "https://doi.org/10.48550/arXiv.2507.06301"
sim_description_common = """
This file contains snapshot data of NewCluster simulation.
For any use of this data, please cite the original publication (Han et al.):
{sim_publication}
Use RUR library to efficiently handle and analyze the data:
https://github.com/sanhancluster/rur
Alternatively, use Pyramis library:
https://github.com/sanhancluster/pyramis"""


[dataset_kw]
compression = "lzf"
shuffle = true
fletcher32 = false
chunks = true


[converted_dtypes_part]
star = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"],
    ["velocity_x","f4"], ["velocity_y","f4"], ["velocity_z","f4"],
    ["mass","f4"], ["identity","i4"], ["levelp","i1"],
    ["family","i1"], ["tag","i1"], ["birth_time","f4"], ["metallicity","f4"], ["initial_mass","f4"],
    ["chem_H","f4"], ["chem_O","f4"], ["chem_Fe","f4"], ["chem_Mg","f4"],
    ["chem_C","f4"], ["chem_N","f4"], ["chem_Si","f4"], ["chem_S","f4"], ["chem_D","f4"],
    ["birth_density","f4"], ["cpu","i2"],
]
dm = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"],
    ["velocity_x","f4"], ["velocity_y","f4"], ["velocity_z","f4"],
    ["mass","f4"], ["identity","i4"], ["levelp","i1"],
    ["family","i1"], ["tag","i1"], ["cpu","i2"],
]
cloud = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"],
    ["velocity_x","f4"], ["velocity_y","f4"], ["velocity_z","f4"],
    ["mass","f4"], ["identity","i4"], ["levelp","i1"],
    ["family","i1"], ["tag","i1"], ["cpu","i2"],
]
tracer = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"],
    ["mass","f4"], ["identity","i4"], ["levelp","i1"],
    ["family","i1"], ["tag","i1"], ["cpu","i2"],
]
sink = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"],
    ["velocity_x","f4"], ["velocity_y","f4"], ["velocity_z","f4"],
    ["mass","f4"], ["identity","i4"], ["birth_time","f4"],
    ["dMsmbh","f4"], ["dMBH_coarse","f4"], ["dMEd_coarse","f4"], ["Esave","f4"],
    ["jsink_x","f4"], ["jsink_y","f4"], ["jsink_z","f4"],
    ["spin_x","f4"], ["spin_y","f4"], ["spin_z","f4"],
    ["spin_magnitude","f4"], ["eps_sink","f4"],
]

[converted_dtypes_cell]
cell = [
    ["position_x","f8"], ["position_y","f8"], ["position_z","f8"], ["level", "i4"],
    ["density","f4"], ["velocity_x","f4"], ["velocity_y","f4"], ["velocity_z","f4"], ["pressure", "f4"],
    ["metallicity","f4"], ["chem_H","f4"], ["chem_O","f4"], ["chem_Fe","f4"], ["chem_Mg","f4"],
    ["chem_C","f4"], ["chem_N","f4"], ["chem_Si","f4"], ["chem_S","f4"], ["chem_D","f4"],
    ["dust_bin01","f4"], ["dust_bin02","f4"], ["dust_bin03","f4"], ["dust_bin04","f4"],
    ["refinement_scalar","f4"], ["scalar_15","f4"], ["potential","f4"], ["cpu","i2"],
]
